# Generated by Django 5.0.3 on 2024-03-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(default='initUser', max_length=225),
        ),
    ]
